//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Practical_Exam_Bitmascot
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Practical_Exam_BitmascotEntities : DbContext
    {
        public Practical_Exam_BitmascotEntities()
            : base("name=Practical_Exam_BitmascotEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<signUpInfo> signUpInfoes { get; set; }

        public System.Data.Entity.DbSet<Practical_Exam_Bitmascot.Models.UserModel> UserModels { get; set; }

        public System.Data.Entity.DbSet<Practical_Exam_Bitmascot.Models.ChangePassworModel> ChangePassworModels { get; set; }
    }
}
